### ISSUE TITLE
关于黑夜模式下的完全覆盖背景图片失效

### ISSUE THREAD

**Issue by Lilac-Dream** [LIlGG/halo-theme-sakura#112]
当前设置：主题切换设置中，设置黑夜模式的情况下，设置一个完全覆盖属性的图片，如图所示：

---
![image](https://user-images.githubusercontent.com/49761134/105821594-ffe8b880-5ff5-11eb-8b55-c364a149e1a2.png)
---

实际效果：黑夜模式下，图片会被黑色完全挡住。
解决办法：可以手动更改一下css，更改一下`background-color`的透明色。
- 主题编辑->style->style.css->Row.8855
```css
body.dark #main-container { 
    background-color: rgba(0,0,0,0.3) !important;
}
```
新问题：纯黑色的黑夜模式也带有了设置的透明色。

所以，主题能否改成，切换到`主题一`的时候，给`body.dark #main-container`添加一个附加的class，比如：切换`主题一`，给他添加一个`theme-kind1`的class，切换到`主题二`，给他添加一个`theme-kind2`的`class`，这样就可以在切换主题的时候，给每个主题分别设置下蒙版的透明度了~
