### ISSUE TITLE
首页文章图文风格，图片能否设置成固定在左边或者右边？

### ISSUE THREAD

**Issue by Lilac-Dream** [LIlGG/halo-theme-sakura#156]
交叉显示在观看的时候，虽然好看，但是对于内容显示不够友好~
因为看内容就需要眼睛要一左一右的晃~
所以能否“图文”风格的时候，图片只固定在左边或者右边？

**Comment by LIlGG** [comment]
主题设置 css 属性
```css
.post-list-thumb-left .post-thumb {
    float: right;
}
```
