### ISSUE TITLE
如何让顶部导航栏进入时就显示

### ISSUE THREAD

**Issue by zbl666** [LIlGG/halo-theme-sakura#196]
如何让顶部导航栏进入时就显示，而不是需要下滑一段距离后，顶部导航栏才显示

**Comment by LIlGG** [comment]
目前没有设置这个选项，不过你可以通过 css 来实现
```css
.is-homepage {
    background: rgba(255,255,255,.95);
    box-shadow: 0 1px 40px -8px rgb(0 0 0 / 50%);
}

.site-header.is-homepage .lower-cantiner {
    display: block;
}
```

eg. 上面的 css 并没有经过完整测试
