### ISSUE TITLE
Github Actions 语句更新

### ISSUE THREAD

**Issue by AirboZH** [LIlGG/halo-theme-sakura#429]
### 目前使用的 Sakura 版本？

无关

### 目前使用的 halo 版本？

无关

### 建议/问题

step `Get pnpm store directory` 中 `Run echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"` 是一个过期的写法，见：https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

更新为
```yml
      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
```
