### ISSUE TITLE
文章页面的图片显示宽度可不可以自定义一下呀

### ISSUE THREAD

**Issue by broliya** [LIlGG/halo-theme-sakura#623]
### 目前使用的 Sakura 版本？

2.4.3

### 目前使用的 halo 版本？

2.20

### 建议/问题

可不可以开放一个设置图片高度的设置呀？就像默认主题的这样![Image](https://github.com/user-attachments/assets/9d65fefe-78c5-4649-b342-837efa8451dc)

![Image](https://github.com/user-attachments/assets/4ea26b3c-e73f-457b-badd-9c0e4683edfc)

sakura图片的默认高度大多数时候显示的图片达不到想要的效果

![Image](https://github.com/user-attachments/assets/7ab9f6cd-79b8-4920-9fda-dfa8cb88f125)

**Comment by LIlGG** [comment]
这种建议直接使用 CSS 设置即可。

```css
.page-header .pattern-center .pattern-attachment-img {
    height: 50rem;
}
```
